# version: '3.8'
services:
  frontend:
    image: krajavar/pmapp-frontend:latest
    ports:
      - "3000:80"                     # Maps port 80 in the container to 3000 on the local machine
    depends_on:
      backend:
        condition: service_healthy    # Wait until backend passes the healthcheck
    restart: always
    working_dir: /app
    # env_file:
    #   - .env.frontend              # Path to frontend environment variables file

  backend:
    image: krajavar/pmapp-backend:latest
    ports:
      - "5000:5000"                       # Maps port 80 in the container to 5000 on the local machine
    env_file:
      - .env.backend               # Path to backend environment variables file
    working_dir: /app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]  # Check if backend is responsive
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  default:
    driver: bridge