# version: '3.8'
services:
  frontend:
    image: krajavar/pmapp-frontend:latest
    container_name: frontend
    expose:
      - "3000"                     # Expose port 3000 internally for the Docker network
    depends_on:
      backend:
        condition: service_healthy    # Wait until backend passes the healthcheck
    restart: always
    working_dir: /app
    # env_file:
    #   - .env.frontend              # Path to frontend environment variables file

  backend:
    image: krajavar/pmapp-backend:latest
    container_name: backend
    expose:
      - "5000"                       # Expose port 5000 internally for the Docker network
    env_file:
      - .env.backend               # Path to backend environment variables file
    working_dir: /app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]  # Check if backend is responsive
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"                  # Expose port 80 externally
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Mount the custom Nginx configuration
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    restart: always

networks:
  default:
    driver: bridge